### ISSUE TITLE
In watch list, support view as Text

### ISSUE THREAD

**Issue by Avasam** [aldelaro5/dolphin-memory-engine#100]
Here is my use-case for it, this array of bytes is a text string:
![image](https://github.com/aldelaro5/dolphin-memory-engine/assets/1350584/a380ccfb-c565-4653-9a42-086dc27f8c02)
show here is d-pad + PS2 face button notation

**Comment by dreamsyntax** [comment]
I think the idea is `array of chars` with no stop condition. 

I'm fine with either naming choice.
Would Japanese Characters display properly? There are plenty of games with them.

**Comment by cristian64** [comment]
Japanese characters? You got me here. I was really thinking of just ASCII characters and nothing else. Any hex editor out there that would show UTF-8 or things like that?

**Comment by Avasam** [comment]
> Just to clarify, isn't the current `string` watch type good enough?

I mean the value view, not the type
![image](https://github.com/aldelaro5/dolphin-memory-engine/assets/1350584/05d6c58c-5443-4190-9afb-e2e5759b626f)

As for the supported character set, whatever the Memory Viewer currently does is fine.

**Comment by Avasam** [comment]
> Just to clarify, isn't the current `string` watch type good enough?

I just updated to 0.9 I think that's a new option? Looks like it does exactly what I'm asking for

![image](https://github.com/aldelaro5/dolphin-memory-engine/assets/1350584/57742877-709d-49b8-84c7-d988ff07e241)

**Comment by cristian64** [comment]
I think `string` has been a long-standing watch type. That's why we thought what you wanted is a non-null-character-terminated array of chars, like hex editors would do (showing ` ` for null characters, and `.` for non-ASCII characters, etc.).

**Comment by Avasam** [comment]
Sorry for the confusion. I feel silly if that was under my nose the entire time.
