### ISSUE TITLE
Entering extra digits when adding watch crashes the program

### ISSUE THREAD

**Issue by MORImementos** [aldelaro5/dolphin-memory-engine#101]
![image](https://github.com/aldelaro5/dolphin-memory-engine/assets/108246578/f4965158-a039-4ac2-922a-7a19e64d554e)

I had an extra digit on accident and it crashed the program. Tried it again and was able to replicate it

**Comment by cristian64** [comment]
@dreamsyntax It seems this was fixed in https://github.com/aldelaro5/dolphin-memory-engine/pull/97/commits/2cd7c78375f75dc78aaeb00527cb3f07fcd3cb3a.

We just need a new release.

**Comment by dreamsyntax** [comment]
Ok, I will release 0.9.1 eod if the MacOS PR is still stagnant today.

**Comment by dreamsyntax** [comment]
Since I ended up merging the MacOS PR, will hold off until the last to 1.0 milestones are done before releasing.
@cristian64 do you have interest in working on either of these?
https://github.com/aldelaro5/dolphin-memory-engine/milestone/1
 Otherwise I may give it a go this week.

**Comment by dreamsyntax** [comment]
Closing as resolved with 1.0 release.
