### ISSUE TITLE
Restore View > Scanner Menu Button

### ISSUE THREAD

**Issue by dreamsyntax** [aldelaro5/dolphin-memory-engine#102]
Some users prefer the explicit toggle for enabling/disabling the Scanner rather than dragging the vertical bar.

Restore this button and behavior that was removed in 0.7.0.

**Comment by cristian64** [comment]
Looking into this issue now.

For reference, the menu action was removed in https://github.com/aldelaro5/dolphin-memory-engine/pull/60/commits/dd7a5adab2ba9405d38346fcd7ab3022358aea5d.
