### ISSUE TITLE
Program is slow and laggy to the point of being unusable

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [aldelaro5/dolphin-memory-engine#114]
For many years I was using a very old version of this tool, and it worked great.  However, after updating to 0.9.0, an issue started happening where 99.99% of the times I open the tool, it starts lagging HARD.  Clicking on any button in the GUI takes upwards of 10 seconds.  Dragging the window around my screen takes ages.  Typing something into the text box can take minutes.  Changed/Unchanged scans aren't worth doing.  Very rarely it'll be full speed with no issues whatsoever when opened, but then I'll close it and open it again, and it's back to its laggy self.  This is even true with a completely empty addresses list.

The program itself isn't actually doing anything to warrant the slowness, like generating temp files or using 100% of my CPU, in fact Task Manager shows it's not doing anything at all.  Even when I laggily type into the text box, it's still using only 6.7% of my CPU, 144 MB of RAM, and 0% Disk usage.

PC specs:

- Intel Core i9-10900K
- NVIDIA RTX 2080 SUPER
- 64 GB DDR4 Memory
- Samsung EVO 2TB SSD
- Windows 10 x64 Build 19045.3803

Definitely not a machine it should be lagging on.  I even went to the extreme of setting all the timer/address update settings to very high amounts of time, like 10000 ms, but it made no difference.  Plus, if it's not laggy on rare occasions, any user setting can't be the issue.  I don't see any generated logs so if there's any other info I could give, I will.

**Comment by aldelaro5** [comment]
It seems 0.9.0 isn't the latest version, I recall this was reported by someone else too.

Try with this version and let us know: https://github.com/aldelaro5/dolphin-memory-engine/releases/tag/v1.0.0

**Comment by dreamsyntax** [comment]
Fwiw, you should also be seeing this in 0.5.0

**Comment by cristian64** [comment]
The fact that the application can be laggy even when there are not addresses in the watch list is odd.

Some questions:
- Do you have any other system available that you can test on?
- Does it perform any better if running with elevated permissions?
- What if the auto-hook mechanism is unticked?
- Does it make any difference when Dolphin is present vs not present?
- Does it make any difference when Dolphin is idling vs running a game?

Things that would be interesting to see as well:

- The flame graph when executed in VTune or equivalent
- The output in Windows' Process Monitor, in case there is any action that is failing or timing out for some reason
- The output in Windows' Event Viewer

**Comment by dreamsyntax** [comment]
> The fact that the application can be laggy even when there are not addresses in the watch list is odd.
> 
> Some questions:
> - Do you have any other system available that you can test on?
> - Does it perform any better if running with elevated permissions?
> - What if the auto-hook mechanism is unticked?
> - Does it make any difference when Dolphin is present vs not present?
> - Does it make any difference when Dolphin is idling vs running a game?
> 
> Things that would be interesting to see as well:
> 
> - The flame graph when executed in VTune or equivalent
> - The output in Windows' Process Monitor, in case there is any action that is failing or timing out for some reason
> - The output in Windows' Event Viewer

Its very common, I can reproduce it in windows only. This users issue lines up with the other issue. I will be curious to see if 1.0.0 has it or not given the cache removal.

Has nothing to do with any of the new features as its present in 0.5.0, and probably 0.3.0 too.

Open order seems to matter, but doesnt guarantee it wont lag. See the linked issue comment.

**Comment by SlyCooperReloadCoded** [comment]
Well, I've been using it for a while, and the issue seems to be gone.  Good, because I've been really needing it, and playing no-lag roulette was getting tiring.
