### ISSUE TITLE
Feature: Copy address of pointer level

### ISSUE THREAD

**Issue by dreamsyntax** [aldelaro5/dolphin-memory-engine#160]
For pointers of n depth, you can "Browse memory at" to open the Memory Viewer to this address.

![image](https://github.com/aldelaro5/dolphin-memory-engine/assets/14857235/6c3132ae-10cb-4bd4-88bd-571849c7e957)

Currently there is no way to 'Copy' a particular depth's address. For example, given the below image:
![image](https://github.com/aldelaro5/dolphin-memory-engine/assets/14857235/4ac5973d-d1a4-4110-891f-19cc96127b7a)

If I wanted to copy level 2's address for use in Dolphin's Breakpoint feature I have to manually open this Address edit pane and type it myself in Dolphin, or utilize the "Browse memory at" and then right click -> add to watch -> copy to clipboard rather than hitting ok -> closing the dialog.

This has the potential to be made much simpler by either allowing copying directly from the Address edit pane or adding a dialog option when right clicking an address in the watchlist.

**Comment by jahorta** [comment]
So I took a shot at this, but I would like some feedback before making a PR. I implemented a right click menu entry for copying the address, but I am unsure if I put it in a good position in the right click menu. Currently I have it below the copy option (see below), but it might also work below the browse at address option. Thoughts?

When right clicking a non-pointer
![Sample copy addresses non-pointer](https://github.com/aldelaro5/dolphin-memory-engine/assets/8341369/7c15d804-bbea-417f-9dbb-6e767457ed63)

When right clicking a pointer
![Sample Copy Addresses Pointer](https://github.com/aldelaro5/dolphin-memory-engine/assets/8341369/3e6cd0a1-7bed-4a41-a4b4-e4d1826823bf)

**Comment by dreamsyntax** [comment]
> So I took a shot at this, but I would like some feedback before making a PR. I implemented a right click menu entry for copying the address, but I am unsure if I put it in a good position in the right click menu. Currently I have it below the copy option (see below), but it might also work below the browse at address option. Thoughts?
> 
> When right clicking a non-pointer
> ![Sample copy addresses non-pointer](https://github.com/aldelaro5/dolphin-memory-engine/assets/8341369/7c15d804-bbea-417f-9dbb-6e767457ed63)
> 
> When right clicking a pointer
> ![Sample Copy Addresses Pointer](https://github.com/aldelaro5/dolphin-memory-engine/assets/8341369/3e6cd0a1-7bed-4a41-a4b4-e4d1826823bf)
> 
> 
> 

It looks good to me. I see it being an infrequent action. The positioning doesn't matter too much. I'm unclear on what keyboard shortcuts you picked, but that can be adjusted in the PR. You can open a "draft PR" so we can look at your code and try out the changes while its in a state you consider incomplete/not ready to merge.
