### ISSUE TITLE
Hooking on macOS Sequoia not working

### ISSUE THREAD

**Issue by mv-stns** [aldelaro5/dolphin-memory-engine#177]
Hooking on macOS Sequoia on the M1 Max MacBook Pro isn't working.
Any further information i can provide?

**Comment by dreamsyntax** [comment]
Did you sign and follow the instructions for mac? Did it work for you before upgrading to macOS 15?

**Comment by mv-stns** [comment]
Yes, I followed the instructions, but I didn't use the memory engine before.

**Comment by dreamsyntax** [comment]
I do not have a mac so I cannot confirm if there are new restrictions breaking this on macOS 15.

@campital or @EndangeredNayla any chance you could confirm?

**Comment by dreamsyntax** [comment]
> Yes, I followed the instructions, but I didn't use the memory engine before.

Just to be 100% sure, you used the signing script on Dolphin.app and the dolphin-memory-engine executable? The script must sign both.

**Comment by mv-stns** [comment]
WAIT. I just noticed i skipped the Dolphin Signing.

**Comment by mv-stns** [comment]
Okay but that didnt fix it tho.

**Comment by EndangeredNayla** [comment]
It works fine for me. What version of dolphin are you using mv-stns?

**Comment by EndangeredNayla** [comment]
> dolphin-memory-engine

You only need to sign the dolphin executable the latter isnt true.

**Comment by mv-stns** [comment]
> It works fine for me. What version of dolphin are you using mv-stns?
Version 2409

**Comment by mv-stns** [comment]
> It works fine for me. What version of dolphin are you using mv-stns?

Did you build it yourself?

**Comment by EndangeredNayla** [comment]
right from the website

**Comment by dreamsyntax** [comment]
I'm assuming this can be closed. It sounds like it works for some people. So it may be signing issue or other restriction.
