### ISSUE TITLE
add command line support for searching certain addresses. 

### ISSUE THREAD

**Issue by ZiroGX2** [aldelaro5/Dolphin-memory-engine#33]
I want to write a batch script that checks a certain address at a specific interval. I feel this would be useful for some people.

**Comment by aldelaro5** [comment]
I agree on it being usefull, however, priority will be pretty low for now as I have a lot planned already for 0.5.  I might do this in a far futur though.

**Comment by dreamsyntax** [comment]
Closing this as I don't intend to maintain a nogui version.
If there is demand for this again and someone else is willing to take up the work, it could be considered.
