### ISSUE TITLE
Make issue: /Dialogs/DlgChangeType.cpp:29:23: error: ‘QOverload’ was not declared in this scope

### ISSUE THREAD

**Issue by KaoticAlmanac** [aldelaro5/Dolphin-memory-engine#34]
Hello, this might be an issue with my QT5 install and if so I apologize, but I am not finding anything else to go on for that front. 

After I clone the repository I proceed to follow the instructions, and when making it, it gets to 52% and crashes with the error:

/home/kevin/Desktop/Dolphin-memory-engine/Source/GUI/MemWatcher/Dialogs/DlgChangeType.cpp: In member function ‘void DlgChangeType::initialiseWidgets()’:
/home/kevin/Desktop/Dolphin-memory-engine/Source/GUI/MemWatcher/Dialogs/DlgChangeType.cpp:29:23: error: ‘QOverload’ was not declared in this scope
   connect(m_cmbTypes, QOverload<int>::of(&QComboBox::currentIndexChanged), this,
                       ^~~~~~~~~
/home/kevin/Desktop/Dolphin-memory-engine/Source/GUI/MemWatcher/Dialogs/DlgChangeType.cpp:29:33: error: expected primary-expression before ‘int’
   connect(m_cmbTypes, QOverload<int>::of(&QComboBox::currentIndexChanged), this,
                                 ^~~
CMakeFiles/Dolphin-memory-engine.dir/build.make:302: recipe for target 'CMakeFiles/Dolphin-memory-engine.dir/GUI/MemWatcher/Dialogs/DlgChangeType.cpp.o' failed
make[2]: *** [CMakeFiles/Dolphin-memory-engine.dir/GUI/MemWatcher/Dialogs/DlgChangeType.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Dolphin-memory-engine.dir/all' failed
make[1]: *** [CMakeFiles/Dolphin-memory-engine.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I am using Qt version 5.5.1 as seen with the command qmake -v

**Comment by calvinpelletier** [comment]
You can either upgrade QT5 to QT5.7 or replace `QOverload::of` with `static_cast<void (QComboBox::*)(int)>` as described in https://stackoverflow.com/questions/47864651/qt-version-checking-and-qoverload-not-defined-in-scope/50755424

**Comment by aldelaro5** [comment]
ok so a long time has passed since then and I don't really want to revert to the old syntax because it makes the code honestly much harder to read than before.  I suggest using a PPA if you are using an older distros, but for now, I am going to close this as there's not much I can do beside making the code annoying to read,
