### ISSUE TITLE
Feature: Undo Search, Save Search, Search Column Sort

### ISSUE THREAD

**Issue by loldbz** [aldelaro5/dolphin-memory-engine#38]
Based on my use of Gecko.NET for Wii memory searches, I would like to propose the following features:

- Undo Search: rolls back your search to the previous search. Huge QOL feature that helps when you're deep in a complex search and just hit the wrong button and go from 100 results found to 0 with no way back.
- Save Search: saves current search to a file to be loaded later. Helpful if you want to take different approaches to a search but want to skip preliminary searching.
- Search Column Sort: being able to sort columns by ascending/descending values can be helpful in performing some search analysis

**Comment by dreamsyntax** [comment]
* Undo search implemented in #61

**Comment by dreamsyntax** [comment]
I'm not really understanding what Search Column Sort would be... does anyone have examples?
