### ISSUE TITLE
Unable to edit labels when a group has children

### ISSUE THREAD

**Issue by Broxzier** [aldelaro5/Dolphin-memory-engine#4]
Double-clicking a label opens the in-line editor to allow renaming an entry, however when a group contains children, none of the labels can be changed (not just the ones that are in the group).
Note that changing values still works just fine.

**Comment by aldelaro5** [comment]
Can confirm and reproduce, that's pretty weird.

Will look into it asap, thanks for reporting.

**Comment by aldelaro5** [comment]
Fixed as of this commit

https://github.com/aldelaro5/Dolphin-memory-engine/commit/72efbf7e54b6c19fd84ce464d8c4df691e92feb9
