### ISSUE TITLE
Feature: Edit multiple values at once

### ISSUE THREAD

**Issue by lastblade** [aldelaro5/dolphin-memory-engine#48]
I'm trying to edit multiple addresses but it just doesn't work.
When i press the value edit shortcut key (F2) when only one address is selected, the value edit is enabled. But if i do the same when multiple addresses are selected, i'm enable to edit them.

**Comment by aldelaro5** [comment]
It's been a while I touched this project, but I am pretty sure it's not supported currently, I will mark it as feature request in case I come back to this.

**Comment by cristian64** [comment]
I'm trying to understand what the workflow / use case is.

What happens when `F2` is pressed while having multiple rows (cells?) selected? Or why would I set the same address in multiple entries?

**Comment by dreamsyntax** [comment]
> I'm trying to understand what the workflow / use case is.
> 
> What happens when `F2` is pressed while having multiple rows (cells?) selected? Or why would I set the same address in multiple entries?

To be clead the multiple cells would have the values all set to whatever the current selection is changed to, like cheat engine.

Value, not the address.
It only applies for same type cells.
Cheat engine does this if you want to see the behavior.

Ex, i have 300 words in a list.
I select all, press F2 or double click the value field, once the current item it edited and I press enter, all 300 word cells will be the same value as well.

**Comment by cristian64** [comment]
> Value, not the address.

This is what made it clear. The title led me astray. I was trying to find a use case for changing all addresses to the same address.

(The title could be reworded.)
