### ISSUE TITLE
Can't search addresses lower than 0x80000000

### ISSUE THREAD

**Issue by Swift016** [aldelaro5/dolphin-memory-engine#55]
See tueidj's post at the bottom of: https://forums.dolphin-emu.org/archive/index.php?thread-38613-2.html

I know this sounds weird and I don't fully understand it myself, but some games seem to use memory addresses below 0x80000000. For example, a game that I am modding stores the currency at 0x7E5BF01C: [removed dead link] (currency is 1700, the second line is a pointer to that address).

I absolutely positively cannot find this 1700 in the 0x80000000+ range in Dolphin or DME. However, Cheat Engine is able to track the values down (but is very screwy with addresses in general).

I am also able to browse this area of memory in Dolphin itself to confirm that there is actually data stored there: [removed dead link]

I brought this issue up to a community that works on ASM hacks for a specific game, and they initially didn't believe that the value I was looking at was actually at this location. This issue seems to be limited to certain games that use unorthodox methods for storing things. It's all above my head but what I know is that DME can't find these values.

**Comment by aldelaro5** [comment]
so ik why this happens and it's a limitation of DME: some games do map memory outside of the usual range, about 25% of them and getting the correct range is what's complicated here.

I can't really address this until this entire thing is migrated to be inside dolphin, but as it is rn, it's not something that can easily be done tbf.

By the way, it CAN happen, it depends on the game, it's for MOST of them, DME works with them which is better than before where you HAD to use CE no matter what and cry :(

**Comment by dreamsyntax** [comment]
Closing this as unfortunately we will never integrate this in Dolphin. For games where its necessary to search in odd locations instead defer to the built in memory widget in Dolphin, which has had many enhancement since 2021.

**Comment by Swift016** [comment]
Dolphin got rid of its memory viewer in v2409, and recommends DME as the current solution.

There is now no longer a solution for games that use addresses lower than 0x8000 0000.

**Comment by Swift016** [comment]
@dreamsyntax @aldelaro5 Thoughts?

**Comment by dreamsyntax** [comment]
Dolphin has not removed the memory viewer, you should be able to continue using it for cases with low address.
