### ISSUE TITLE
(Ver. 0.5.1, 0.5.0, 0.4.0) - Cannot use extended memory with DME

### ISSUE THREAD

**Issue by ashtif** [aldelaro5/Dolphin-memory-engine#58]
Unless I've missed something in the documentation, I'm having a few strange issues with DME on a modified version of Wind Waker.

Using Kirbymimi's Wind Waker Multiplayer mod, I have all settings as normal, but emulated memory must be 64mb, and CPU Clock Override must be 200% minimum (To prevent lag)

Whenever I try to hook DME 0.5.1 or 0.4.0, it unhooks instantly. Whenever I try to hook with DME 0.5.0, it reads every address as storing a value of 0. 

Not completely sure how to counteract this.

**Comment by aldelaro5** [comment]
If the mod needs the extended memory option, DME doesn't yet support it and unfortunately, I don't maintain it much nowadays for multiple reasons like having other projects and DME in general being too limited and I would just want to try to merge it within dolphin itself.

For now, this fork might do what you want, but I cannot guarantee it works and it seems to be a bit behind from lattest version https://github.com/Minty-Meeo/Dolphin-memory-engine/releases/tag/v0.5-beta

**Comment by ashtif** [comment]
Fantastic, thank you very much I'll use this fork for now.

I'm gonna see about possibly finding another fork for the python version as well, or I'll look to see what the fork you've linked does since my program uses DME as a library (the Python version that is).

Thanks Aldelaro.

**Comment by dreamsyntax** [comment]
Added in 0.7.0
