### ISSUE TITLE
Linux Download

### ISSUE THREAD

**Issue by jbagster1014** [aldelaro5/Dolphin-memory-engine#62]
What do i do to run the program on linux with the zip from the releases tab

**Comment by dreamsyntax** [comment]
The program was compiled as a 64-bit elf (GNU Binutils for Ubuntu 2.38).
You may need to mark the program as executable.
```
chmod +x Dolphin-memory-engine
```
and then run it (some DEs allow double click)
```
./Dolphin-memory-engine
```
